version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - DB_DRIVER=sqlite
      - DB_NAME=calc_example
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Для продакшена можно добавить PostgreSQL
# postgres:
#   image: postgres:15-alpine
#   environment:
#     POSTGRES_DB: calc_example
#     POSTGRES_USER: postgres
#     POSTGRES_PASSWORD: password
#   volumes:
#     - postgres_data:/var/lib/postgresql/data
#   ports:
#     - "5432:5432"
#   restart: unless-stopped

volumes:
  postgres_data: 